#!/bin/bash

set -euo pipefail

simpleQ=false
help=false
use_ref=
use_sam=
use_bounds=
use_zoom=
extra_header=
N_wrap=0

while getopts :r:s:e:w:z:x:Qh opt
do
    case "$opt" in
    r)
      use_ref=$OPTARG
      ;;
    s)
      use_sam=$OPTARG
      ;;
    e)
      use_bounds=$OPTARG
      ;;
    x)
      extra_header=$OPTARG
      ;;
    Q)
      simpleQ=true
      ;;
    z)
      use_zoom=$OPTARG
      ;;
    w)
      N_wrap=$OPTARG
      ;;
    h)
      cat <<EOU
Pretty-print alignments; allows focus on boundaries (-e) or specific intervals (-z).
Base usage: -r <REFERENCE> -s <SAM-FILE>

Input is SAM. For bam files use
  samtools view [-h] <bamfile> | showalign -r <REF> -s - [options]

To output wrapped alignments use -w <WIDTH>

-r <fname>        reference file (fasta)
-s <fname>        SAM input (- for STDIN)
-e x,y            ensure alignment includes coordinates [x-y]
-z u,v            zoom / limit alignment to coordinates [x-y]
-w N              pass alignment to wrapalign with width N
-x <pick-list>    pick code to add to header after read name before alignment
                     issue pick -l sam for possibilities
-Q                use simplified quality scheme

                  .....,,,,,aaaaaAAAAAbbbbbBBBBBcccccCCCCCdddddDDDDDeeeeeEEEEEfffffFFFFFgggggGGGGGhhhhhHHHHHiiii
                         3  | 1  | 3  | 1  | 3  | 1  | 3  | 1  | 3  | 1  | 3  | 1  | 3  | 1  | 3  | 1  | 3  | 1 |
                         -- | -- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |--- |---|
                         10 | 10 |100 |100 |1e3 |1e3 |1e4 |1e4 |1e5 |1e5 |1e6 |1e6 |1e7 |1e7 |1e8 |1e8 |1e9 |1e9|
EOU
      exit
      ;;
    :)
      error="Flag $OPTARG needs argument"
      false
      ;;
    ?)
      error="Flag $OPTARG unknown"
      false
      ;;
   esac
done

shift $(($OPTIND-1))

if (( $# > 0 )); then
  echo "Trailing arguments $@ found" 
  false
fi


nerr=0
[[ -n $use_ref ]] || { echo "Need reference (-r)" && ((++nerr)); }
[[ -n $use_sam ]] || { echo "Need sam input (-s)" && ((++nerr)); }

if ((nerr > 0)); then
  echo "errors occurred"
  false
fi


moreargs=
mode_select=aln_allq
mode_wrap=cat

if (( N_wrap > 0 )); then
  mode_wrap="wrapalign $N_wrap"
fi

if $simpleQ; then
  moreargs="$moreargs --sam-qlt-sim"
fi

if [[ -n $use_bounds ]]; then
  moreargs="$moreargs --sam-aln-xy=$use_bounds"
elif [[ -n $use_zoom ]]; then
  moreargs="$moreargs --sam-rbt=$use_zoom"
  mode_select=rbt_alnall
fi

cat $use_sam | pick --sam/$use_ref --sam-aln-prefix='++ ' $moreargs ::1"$extra_header",$mode_select^^%0A,joinall | $mode_wrap


